export const chatContent: Record<string, Record<string, string>> = {
  en: { noRecommendations: "All identified examples conflict with the saved dietary preferences. No dish is suggested. Confirm alternatives with staff.", unpersonalized: "No dietary preferences have been provided; this example does not account for personal restrictions.", explain: 'Example explanation: this is a dish shown in this record. Its ingredients, flavor and preparation need confirmation with the restaurant.', recommend: 'Example suggestion from this menu. Confirm ingredients and your dietary needs with the restaurant before choosing.', price: 'Reference example for two portions. Confirm the portion unit, final price and any extra charges with the restaurant.', unknownPrice: 'The menu price or currency is unknown, so a reference total cannot be calculated.', communicate: 'You can show this question to the server.', question: 'Could you confirm the ingredients and preparation of {dish}? Are there any ingredients I should check?', title: 'Ask about {dish}', empty: 'This record has no identified dishes yet. Add menu information before asking about a particular dish.', uncertain: 'Unidentified dish' },
  ja: { noRecommendations: "確認された例はいずれも保存した食事条件に抵触するため、料理の提案はありません。別の選択肢を店員に確認してください。", unpersonalized: "食事の希望が未設定のため、この例は個人の制限を考慮していません。", explain: '説明の例：この記録にある料理です。食材、味付け、調理方法はお店に確認してください。', recommend: 'このメニューからの提案例です。注文前に食材やご自身の食事制限についてお店に確認してください。', price: '2人前の参考例です。量の単位、最終価格、追加料金はお店に確認してください。', unknownPrice: '価格または通貨が不明なため、参考合計は計算できません。', communicate: 'この質問を店員に見せてください。', question: '{dish}の食材と調理方法を教えてください。確認すべき食材はありますか？', title: '{dish}について質問', empty: 'この記録には確認できた料理がまだありません。特定の料理について質問するにはメニュー情報を追加してください。', uncertain: '未確認の料理' },
  ko: { noRecommendations: "확인된 모든 예시가 저장한 식사 조건과 충돌하여 요리를 추천하지 않아요. 직원에게 다른 선택지를 확인하세요.", unpersonalized: "식사 조건을 설정하지 않아 이 예시는 개인의 제한 사항을 반영하지 않아요.", explain: '설명 예시: 이 기록에 있는 요리입니다. 식재료, 맛과 조리 방법은 식당에 확인하세요.', recommend: '이 메뉴의 제안 예시입니다. 선택하기 전에 식재료와 식이 요구 사항을 식당에 확인하세요.', price: '2인분의 참고 예시입니다. 양의 단위, 최종 가격 및 추가 요금은 식당에 확인하세요.', unknownPrice: '메뉴 가격 또는 통화를 알 수 없어 참고 합계를 계산할 수 없습니다.', communicate: '이 질문을 직원에게 보여 주세요.', question: '{dish}의 식재료와 조리 방법을 알려 주시겠어요? 확인해야 할 식재료가 있나요?', title: '{dish}에 대해 질문', empty: '이 기록에는 아직 확인된 요리가 없습니다. 특정 요리에 대해 질문하려면 메뉴 정보를 추가하세요.', uncertain: '확인되지 않은 요리' },
  es: { noRecommendations: "Todos los ejemplos identificados entran en conflicto con las preferencias guardadas. No se sugiere ningún plato. Consulta alternativas con el personal.", unpersonalized: "No se han indicado preferencias alimentarias; este ejemplo no contempla restricciones personales.", explain: 'Explicación de ejemplo: este plato aparece en el registro. Confirma los ingredientes, el sabor y la preparación con el restaurante.', recommend: 'Sugerencia de ejemplo de este menú. Confirma los ingredientes y tus necesidades alimentarias con el restaurante antes de elegir.', price: 'Ejemplo orientativo para dos raciones. Confirma la unidad, el precio final y los posibles suplementos con el restaurante.', unknownPrice: 'Se desconoce el precio o la moneda, por lo que no se puede calcular un total orientativo.', communicate: 'Puedes mostrar esta pregunta al personal.', question: '¿Podrían confirmar los ingredientes y la preparación de {dish}? ¿Hay algún ingrediente que deba comprobar?', title: 'Preguntar por {dish}', empty: 'Este registro aún no tiene platos identificados. Añade información del menú antes de preguntar por un plato concreto.', uncertain: 'Plato sin identificar' },
  'zh-CN': { noRecommendations: "已识别的固定样例均与已保存的饮食偏好明确冲突，本次不推荐菜品。请向店员确认其他选择。", unpersonalized: "尚未设置饮食偏好，此示例未结合个人饮食限制。", explain: '示例解释：这是当前记录中的一道菜。食材、口味和具体做法仍需向餐厅确认。', recommend: '这是当前菜单中的示例建议。选择前请向餐厅确认食材及个人饮食需求。', price: '这是两份菜品的参考示例。份量单位、最终价格及额外收费请向餐厅确认。', unknownPrice: '菜单价格或币种不明确，无法计算参考合计。', communicate: '可以把下面的问题给店员看。', question: '请问{dish}使用哪些食材，具体怎么做？有什么配料需要进一步确认？', title: '询问{dish}', empty: '这条记录还没有可确认的菜品。请补充菜单信息后再询问具体菜品。', uncertain: '未确认菜品' }
};

export function twoPortions(amount: string) {
  const parts = amount.split('.'); const scale = (parts[1] || '').length;
  const digits = (BigInt(parts.join('')) * 2n).toString().padStart(scale + 1, '0');
  return scale ? `${digits.slice(0, -scale)}.${digits.slice(-scale)}` : digits;
}
