import { randomUUID } from 'node:crypto';
import { mkdirSync, writeFileSync, renameSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import sharp from 'sharp';
import { ApiError, reject, validate, hash } from './contract.ts';
import type { Json } from './contract.ts';
import type { JobHandler } from './jobs.ts';
import { content } from './image-card-content.ts';

interface Options {
  database: DatabaseSync; directory: string; now: () => number;
  getContext: (id: string, owner: string) => any; baseUrl: () => string;
  scenario?: string; delayMs?: number;
}
/** Generated bytes are mocked; their identity, files and authorized delivery are real. */
export function createImageTranslation(options: Options) {
  const { database, directory, getContext, now, baseUrl } = options;
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  database.exec(`CREATE TABLE IF NOT EXISTS image_artifacts (
    id TEXT PRIMARY KEY, job_id TEXT NOT NULL, owner TEXT NOT NULL, context_id TEXT NOT NULL REFERENCES contexts(id),
    image_id TEXT NOT NULL, path TEXT NOT NULL, content_hash TEXT NOT NULL, descriptor TEXT NOT NULL);`);
  function descriptor(row: any) {
    const context = getContext(String(row.context_id), String(row.owner));
    return { ...JSON.parse(row.descriptor), remoteUrl: `${baseUrl()}/v1/image-artifacts/${encodeURIComponent(row.id)}`,
      remoteUrlExpiresAt: context.expires_at };
  }
  const handler: JobHandler = {
    purpose: 'record',
    prepare(request, snapshot, asset) {
      const image = snapshot.snapshot.images.find((item: Json) => item.imageId === request.target.imageId);
      if (!image || !image.assetId || image.assetId !== request.input.assetId) reject(409, 'DEPENDENCY_MISSING');
      return [asset(image.assetId, image.imageId, image.kind)];
    },
    async generate({ request, snapshot, job, images }) {
      const source = snapshot.snapshot.images.find((image: Json) => image.imageId === request.target.imageId);
      if (request.input.targetLanguage === 'zh-CN' || source.kind === 'dish') return { state: 'not_required',
        reasonKey: request.input.targetLanguage === 'zh-CN' ? 'images.already_chinese' : 'images.no_translatable_text' };
      if (options.delayMs) await new Promise((resolve) => setTimeout(resolve, options.delayMs));
      if (options.scenario === 'translation-failure') throw new ApiError(503, 'TEMPORARY_FAILURE', true);
      const metadata = await sharp(images[0]).metadata();
      const width = metadata.width!; const height = metadata.height!;
      const label = content[request.input.targetLanguage].name;
      const panelHeight = Math.min(height, Math.max(80, Math.round(width * 0.16)));
      const escaped = label.replace(/[&<>]/g, (letter: string) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[letter]!));
      const overlay = Buffer.from(`<svg width="${width}" height="${panelHeight}"><rect width="100%" height="100%" fill="#fffbea"/><text x="18" y="28" fill="#315d43" font-size="18">MOCK TRANSLATION · ${request.input.targetLanguage}</text><text x="18" y="60" fill="#243d2c" font-size="22">${escaped} · ¥28</text></svg>`);
      const bytes = await sharp(images[0]).composite([{ input: overlay, top: 0, left: 0 }]).png().toBuffer();
      const owner = database.prepare('SELECT owner FROM contexts WHERE id=?').get(job.contextId)!.owner as string;
      getContext(job.contextId, owner);
      const id = randomUUID(); const path = join(directory, `${id}.png`); const temporary = `${path}.tmp`;
      writeFileSync(temporary, bytes, { mode: 0o600 }); renameSync(temporary, path);
      const artifact = { id, imageId: request.target.imageId, kind: 'translation', contentLanguage: request.input.targetLanguage,
        assetId: id, remoteUrl: `${baseUrl()}/v1/image-artifacts/${id}`,
        remoteUrlExpiresAt: new Date(now() + 3600000).toISOString(), mimeType: 'image/png', width, height };
      database.prepare('INSERT INTO image_artifacts VALUES (?,?,?,?,?,?,?,?)').run(id, job.jobId, owner, job.contextId,
        request.target.imageId, path, hash(bytes), JSON.stringify(artifact));
      return { state: 'ready', artifact };
    },
    validateOutput(output, frozen) {
      validate('ImageTranslationOutput', output);
      if (output.state === 'ready' && (output.artifact.imageId !== frozen.request.target.imageId ||
          output.artifact.contentLanguage !== frozen.request.input.targetLanguage)) reject(409, 'DEPENDENCY_MISSING');
    }
  };
  return { handler,
    decorate(job: Json) {
      if (job.kind !== 'image_translation' || job.output?.state !== 'ready') return job;
      const row = database.prepare('SELECT * FROM image_artifacts WHERE id=? AND job_id=?').get(job.output.artifact.id, job.jobId);
      if (!row) return reject(409, 'DEPENDENCY_MISSING');
      return { ...job, output: { ...job.output, artifact: descriptor(row) } };
    },
    download(id: string, owner: string) {
      const row = database.prepare('SELECT * FROM image_artifacts WHERE id=?').get(id);
      if (!row) return reject(404, 'NOT_FOUND');
      if (row.owner !== owner) return reject(403, 'FORBIDDEN');
      getContext(String(row.context_id), owner);
      let bytes: Buffer; try { bytes = readFileSync(String(row.path)); } catch { return reject(409, 'DEPENDENCY_MISSING'); }
      if (hash(bytes) !== row.content_hash) reject(409, 'DEPENDENCY_MISSING');
      return bytes;
    }
  };
}
