const COPY = {
  en: { title: 'Ask about this menu', entry: 'Ask about this menu', placeholder: 'Ask about the dishes…', send: 'Send', empty: 'Ask about any dish in this record, or try a suggestion below.', mock: 'Replies use fixed examples for this preview.', sending: 'Sending…', waiting: 'Preparing a reply…', partial: 'Reply in progress', complete: 'Saved on this device', failed: 'The reply could not be completed.', busy: 'Wait for this reply before sending another question. You can keep typing.', offline: 'Connect to send a new question. Saved messages are still available.', saveFailed: 'This reply has not been saved on this device.', retrySave: 'Save again', missing: 'This record is unavailable.', error: 'The question could not be sent. Your text is still here.', openDish: 'View dish', card: 'Show this to the server', back: 'Back to menu',
    questions: [{ id: 'explain', label: 'Explain dishes', text: 'Explain the dishes on this menu.' }, { id: 'recommend', label: 'Recommend dishes', text: 'Suggest dishes from this menu.' }, { id: 'price', label: 'Estimate a price', text: 'Show a reference price for two portions of a dish.' }, { id: 'communicate', label: 'Ask the server', text: 'Help me ask the server about a dish.' }] },
  ja: { title: 'このメニューについて質問', entry: 'このメニューについて質問', placeholder: '料理について質問…', send: '送信', empty: 'この記録の料理について質問するか、下の候補を選んでください。', mock: 'このプレビューの回答は固定の例です。', sending: '送信中…', waiting: '回答を準備中…', partial: '回答中', complete: 'この端末に保存済み', failed: '回答を完了できませんでした。', busy: '回答を待ってから次の質問を送信してください。入力は続けられます。', offline: '新しい質問には接続が必要です。保存済みの会話は読めます。', saveFailed: 'この回答は端末に保存されていません。', retrySave: '再保存', missing: 'この記録は利用できません。', error: '質問を送信できませんでした。入力内容は保持されています。', openDish: '料理を見る', card: '店員に見せる内容', back: 'メニューに戻る',
    questions: [{ id: 'explain', label: '料理の説明', text: 'このメニューの料理を説明してください。' }, { id: 'recommend', label: 'おすすめ', text: 'このメニューから料理を提案してください。' }, { id: 'price', label: '参考金額', text: '料理を2人前頼んだ場合の参考金額を示してください。' }, { id: 'communicate', label: '店員に質問', text: '料理について店員に質問するのを手伝ってください。' }] },
  ko: { title: '이 메뉴에 대해 질문', entry: '이 메뉴에 대해 질문', placeholder: '요리에 대해 질문하세요…', send: '보내기', empty: '이 기록의 요리에 대해 질문하거나 아래 제안을 선택하세요.', mock: '이 미리보기의 답변은 고정된 예시입니다.', sending: '전송 중…', waiting: '답변 준비 중…', partial: '답변 중', complete: '이 기기에 저장됨', failed: '답변을 완료하지 못했습니다.', busy: '답변을 기다린 후 다음 질문을 보내세요. 계속 입력할 수 있습니다.', offline: '새 질문을 보내려면 연결하세요. 저장된 대화는 읽을 수 있습니다.', saveFailed: '이 답변은 기기에 저장되지 않았습니다.', retrySave: '다시 저장', missing: '이 기록을 사용할 수 없습니다.', error: '질문을 보내지 못했습니다. 입력 내용은 유지됩니다.', openDish: '요리 보기', card: '직원에게 보여줄 내용', back: '메뉴로 돌아가기',
    questions: [{ id: 'explain', label: '요리 설명', text: '이 메뉴의 요리를 설명해 주세요.' }, { id: 'recommend', label: '요리 추천', text: '이 메뉴에서 요리를 추천해 주세요.' }, { id: 'price', label: '참고 가격', text: '요리 2인분의 참고 가격을 보여 주세요.' }, { id: 'communicate', label: '직원에게 질문', text: '요리에 대해 직원에게 질문하도록 도와주세요.' }] },
  es: { title: 'Pregunta sobre este menú', entry: 'Pregunta sobre este menú', placeholder: 'Pregunta sobre los platos…', send: 'Enviar', empty: 'Pregunta por un plato de este registro o elige una sugerencia.', mock: 'Las respuestas de esta vista previa son ejemplos fijos.', sending: 'Enviando…', waiting: 'Preparando una respuesta…', partial: 'Respuesta en curso', complete: 'Guardado en este dispositivo', failed: 'No se pudo completar la respuesta.', busy: 'Espera la respuesta antes de enviar otra pregunta. Puedes seguir escribiendo.', offline: 'Conéctate para enviar una pregunta. Puedes leer los mensajes guardados.', saveFailed: 'Esta respuesta no se ha guardado en el dispositivo.', retrySave: 'Guardar de nuevo', missing: 'Este registro no está disponible.', error: 'No se pudo enviar la pregunta. El texto sigue aquí.', openDish: 'Ver plato', card: 'Texto para mostrar al personal', back: 'Volver al menú',
    questions: [{ id: 'explain', label: 'Explicar platos', text: 'Explica los platos de este menú.' }, { id: 'recommend', label: 'Recomendar platos', text: 'Sugiere platos de este menú.' }, { id: 'price', label: 'Estimar precio', text: 'Muestra un precio orientativo para dos raciones de un plato.' }, { id: 'communicate', label: 'Preguntar al personal', text: 'Ayúdame a preguntar al personal sobre un plato.' }] },
  'zh-CN': { title: '问问这份菜单', entry: '问问这份菜单', placeholder: '输入想问的菜品问题…', send: '发送', empty: '可以问这条记录中的任何菜品，也可以使用下方快捷问题。', mock: '当前预览使用固定示例回复。', sending: '发送中…', waiting: '正在准备回复…', partial: '正在回复', complete: '已保存到本机', failed: '回复未能完成。', busy: '请等待当前回复后再发送下一问，期间可以继续输入。', offline: '联网后可以发送新问题，已保存的对话仍可阅读。', saveFailed: '这条回复尚未保存到本机。', retrySave: '重新保存', missing: '这条记录无法读取。', error: '问题未能发送，输入内容仍保留。', openDish: '查看菜品', card: '给店员看的内容', back: '返回菜单',
    questions: [{ id: 'explain', label: '解释菜品', text: '请解释这份菜单中的菜品。' }, { id: 'recommend', label: '推荐菜品', text: '请从这份菜单中推荐菜品。' }, { id: 'price', label: '参考算价', text: '请展示一道菜两份的参考价格。' }, { id: 'communicate', label: '询问店员', text: '请帮我向店员询问一道菜。' }] }
};
const READING = {
  en: { clearDraft: 'Clear draft', newReply: 'View new reply', draftSaveFailed: 'Your draft change is not saved on this device. Try saving again.', positionSaveFailed: 'Your reading position is not saved. Try saving again.' },
  ja: { clearDraft: '下書きを消す', newReply: '新しい回答を見る', draftSaveFailed: '下書きの変更は端末に保存されていません。再保存してください。', positionSaveFailed: '閲覧位置を保存できませんでした。再保存してください。' },
  ko: { clearDraft: '초안 지우기', newReply: '새 답변 보기', draftSaveFailed: '초안 변경 내용이 기기에 저장되지 않았습니다. 다시 저장하세요.', positionSaveFailed: '읽던 위치를 저장하지 못했습니다. 다시 저장하세요.' },
  es: { clearDraft: 'Borrar borrador', newReply: 'Ver respuesta nueva', draftSaveFailed: 'El cambio del borrador no está guardado en este dispositivo. Intenta guardarlo de nuevo.', positionSaveFailed: 'No se guardó la posición de lectura. Intenta guardarla de nuevo.' },
  'zh-CN': { clearDraft: '清空草稿', newReply: '查看新回复', draftSaveFailed: '草稿更改尚未保存到本机，请重试保存。', positionSaveFailed: '阅读位置尚未保存，请重试保存。' }
};
for (const language of Object.keys(COPY)) Object.assign(COPY[language], READING[language]);
function getChatCopy(language) { return COPY[language] || COPY.en; }
module.exports = { getChatCopy };
