const COPY = {
  en: { title: 'Dietary preferences', pending: 'Not checked against your current preferences yet.', checking: 'Checking your current preferences. Previous hints are not current.', current: 'Checked against your current preferences', failed: 'Check failed. Still waiting to check your current preferences.', conflict: 'Conflicts with your preferences', possible_conflict: 'Possible conflict — confirm with staff', unknown: 'Suitability unknown — confirm with staff', start: 'Check preferences', retry: 'Retry preference check', continue: 'Continue preference check', saveFailed: 'These hints are not saved on this device.', retrySave: 'Retry saving hints', error: 'Could not update the check. Saved explanations remain available.' },
  ja: { title: '食事の希望', pending: '現在の食事条件ではまだ確認していません。', checking: '現在の条件で確認中です。以前の注意事項は最新ではありません。', current: '現在の食事条件で確認済み', failed: '確認に失敗しました。現在の条件では引き続き未確認です。', conflict: '食事条件に抵触します', possible_conflict: '抵触する可能性があります。店員に確認してください', unknown: '適合するか不明です。店員に確認してください', start: '食事条件を確認', retry: '確認を再試行', continue: '確認を続ける', saveFailed: '注意事項は端末に保存されていません。', retrySave: '注意事項の保存を再試行', error: '確認状況を更新できませんでした。保存済みの説明は読めます。' },
  ko: { title: '식사 선호', pending: '현재 식사 조건으로 아직 확인하지 않았어요.', checking: '현재 조건으로 확인 중이에요. 이전 안내는 최신 정보가 아니에요.', current: '현재 식사 조건으로 확인됨', failed: '확인에 실패했어요. 현재 조건으로 아직 확인이 필요해요.', conflict: '식사 조건과 충돌해요', possible_conflict: '충돌할 수 있어요. 직원에게 확인하세요', unknown: '적합 여부를 알 수 없어요. 직원에게 확인하세요', start: '식사 조건 확인', retry: '확인 재시도', continue: '확인 계속하기', saveFailed: '이 안내는 기기에 저장되지 않았어요.', retrySave: '안내 저장 재시도', error: '확인 상태를 갱신하지 못했어요. 저장한 설명은 계속 볼 수 있어요.' },
  es: { title: 'Preferencias alimentarias', pending: 'Todavía no se ha comprobado con tus preferencias actuales.', checking: 'Comprobando las preferencias actuales. Las indicaciones anteriores no están actualizadas.', current: 'Comprobado con tus preferencias actuales', failed: 'La comprobación falló. Las preferencias actuales siguen pendientes.', conflict: 'Incompatible con tus preferencias', possible_conflict: 'Posible incompatibilidad: consulta al personal', unknown: 'Compatibilidad desconocida: consulta al personal', start: 'Comprobar preferencias', retry: 'Reintentar comprobación', continue: 'Continuar comprobación', saveFailed: 'Estas indicaciones no están guardadas en el dispositivo.', retrySave: 'Reintentar guardar indicaciones', error: 'No se pudo actualizar la comprobación. Las explicaciones guardadas siguen disponibles.' },
  'zh-CN': { title: '饮食偏好提示', pending: '尚未按当前偏好完成检查。', checking: '正在按当前偏好检查，旧提示尚未更新。', current: '已按当前偏好完成检查', failed: '检查失败，仍待按当前偏好检查。', conflict: '与偏好明确冲突', possible_conflict: '可能冲突，请向店员确认', unknown: '信息不足，请向店员确认', start: '检查饮食偏好', retry: '重试偏好检查', continue: '继续偏好检查', saveFailed: '这些提示尚未保存到本机。', retrySave: '重试保存提示', error: '未能更新检查状态，已保存的菜品解释仍可查看。' }
};
function getDietaryCopy(language) { return { ...(COPY[language] || COPY.en) }; }
module.exports = { getDietaryCopy };
