const COPY = {
  en: { title: 'Dish details', dishes: 'Dishes in this photo', details: 'Ingredients, preparation and how to eat', uncertainty: 'Confirm with staff', unknownName: 'Dish not identified', unknownPrice: 'Price unknown', original: 'Check original photo', mock: 'Fixed example content. Confirm actual ingredients and prices with staff.', noCards: 'No dish cards were found for this photo. Check the original or provide a clearer photo.', queued: 'Dish cards queued', running: 'Preparing dish cards', succeeded: 'Dish cards ready', failed: 'Dish processing failed', cancelled: 'Processing cancelled', expired: 'Processing expired', unstarted: 'Dish processing has not started', accepted: 'Processing has been accepted. You can leave and return to this record later.', saveFailed: 'The result is ready but could not be saved on this device. Free space and retry saving.', retrySave: 'Retry saving result', readFailed: 'Could not retrieve progress. Saved content remains available.', missing: 'This dish is no longer available in the record.', back: 'Back' },
  ja: { title: '料理の詳細', dishes: 'この写真の料理', details: '食材・調理法・食べ方', uncertainty: '店員に確認すること', unknownName: '料理を特定できません', unknownPrice: '価格不明', original: '元画像で確認', mock: '固定の模擬内容です。実際の食材や価格は店員に確認してください。', noCards: 'この写真から料理カードは見つかりませんでした。元画像を確認するか、鮮明な写真を追加してください。', queued: '料理カードの処理待ち', running: '料理カードを作成中', succeeded: '料理カードを作成済み', failed: '料理の処理に失敗', cancelled: '処理を中止しました', expired: '処理の期限が切れました', unstarted: '料理の処理は未開始です', accepted: '処理を受け付けました。離れても、後でこの記録に戻れます。', saveFailed: '結果はできていますが、端末に保存できませんでした。空き容量を確認して再試行してください。', retrySave: '結果の保存を再試行', readFailed: '進捗を取得できませんでした。保存済みの内容は利用できます。', missing: 'この記録で料理を開けません。', back: '戻る' },
  ko: { title: '요리 상세', dishes: '이 사진의 요리', details: '재료, 조리법과 먹는 법', uncertainty: '직원에게 확인할 사항', unknownName: '요리를 확인할 수 없어요', unknownPrice: '가격 미확인', original: '원본 사진 확인', mock: '고정된 모의 예시입니다. 실제 재료와 가격은 직원에게 확인하세요.', noCards: '이 사진에서 요리 카드를 찾지 못했어요. 원본을 확인하거나 더 선명한 사진을 추가하세요.', queued: '요리 카드 대기 중', running: '요리 카드 준비 중', succeeded: '요리 카드 준비됨', failed: '요리 처리 실패', cancelled: '처리가 취소됐어요', expired: '처리 기간이 지났어요', unstarted: '요리 처리가 시작되지 않았어요', accepted: '처리가 접수됐어요. 나중에 이 기록으로 돌아와 확인할 수 있어요.', saveFailed: '결과가 준비됐지만 기기에 저장하지 못했어요. 공간을 확보하고 다시 저장하세요.', retrySave: '결과 저장 재시도', readFailed: '진행 상태를 가져오지 못했어요. 저장한 내용은 볼 수 있어요.', missing: '이 기록에서 요리를 찾을 수 없어요.', back: '뒤로' },
  es: { title: 'Detalles del plato', dishes: 'Platos de esta foto', details: 'Ingredientes, preparación y cómo comerlo', uncertainty: 'Confirma con el personal', unknownName: 'Plato sin identificar', unknownPrice: 'Precio desconocido', original: 'Consultar foto original', mock: 'Contenido de ejemplo fijo. Confirma los ingredientes y precios reales con el personal.', noCards: 'No se encontraron platos en esta foto. Consulta el original o añade una foto más clara.', queued: 'Platos en cola', running: 'Preparando los platos', succeeded: 'Platos disponibles', failed: 'Error al procesar los platos', cancelled: 'Procesamiento cancelado', expired: 'Procesamiento caducado', unstarted: 'El procesamiento no ha empezado', accepted: 'El procesamiento está aceptado. Puedes salir y volver a este registro más tarde.', saveFailed: 'El resultado está listo, pero no se pudo guardar en el dispositivo. Libera espacio y vuelve a guardarlo.', retrySave: 'Reintentar guardado del resultado', readFailed: 'No se pudo consultar el progreso. El contenido guardado sigue disponible.', missing: 'Este plato ya no está disponible en el registro.', back: 'Volver' },
  'zh-CN': { title: '菜品详情', dishes: '当前图片的菜品', details: '食材、做法与吃法', uncertainty: '待确认事项', unknownName: '菜品身份未确定', unknownPrice: '价格未知', original: '查看原图核对', mock: '固定模拟内容，实际食材与价格请向店员确认。', noCards: '当前图片没有识别到菜品卡片，请核对原图或补充更清晰的照片。', queued: '菜品卡片排队中', running: '正在生成菜品卡片', succeeded: '菜品卡片已完成', failed: '菜品处理失败', cancelled: '处理已取消', expired: '处理已过期', unstarted: '尚未开始菜品处理', accepted: '处理已接收，可以离开并稍后回到这条记录查看。', saveFailed: '结果已完成，但尚未保存到本机。请清理空间后重试保存。', retrySave: '重试保存结果', readFailed: '未能获取进度，已保存内容仍可查看。', missing: '这条记录中找不到该菜品。', back: '返回' }
};
function getDishesCopy(language) { return Object.assign({}, COPY[language] || COPY.en); }
function presentDish(card, copy) {
  return Object.assign({}, card, { displayName: card.nameZh || card.localizedName || copy.unknownName,
    secondaryName: card.localizedName && card.localizedName !== card.nameZh ? card.localizedName : null,
    priceLabel: card.price.amount === null ? copy.unknownPrice : [card.price.currency, card.price.amount, card.price.unit].filter(Boolean).join(' · '),
    priceRaw: card.price.rawText, uncertainIdentity: card.nameZh === null && card.localizedName === null });
}
module.exports = { getDishesCopy, presentDish };
