const COPY = {
  en: { original: 'Original', translation: 'Translated', unstarted: 'Image translation not started', queued: 'Image translation queued', running: 'Translating image', ready: 'Translated image ready. Switch when you like.', failed: 'Image translation failed', cancelled: 'Image translation cancelled', expired: 'Image translation expired', notRequired: 'No image translation needed', alreadyChinese: 'The original is already in Chinese', noText: 'No text to translate in this dish photo', originalSave: 'Original on this device', translationSave: 'Translation on this device', pending: 'Not saved on this device', saving: 'Saving on this device', saved: 'Saved on this device', saveFailed: 'Not saved. Unavailable offline.', retrySave: 'Retry saving image', missingTranslation: 'Translated image is not available on this device. Save it when online.', choiceFailed: 'Your image choice could not be saved', retryChoice: 'Retry saving choice', readFailed: 'Could not refresh the image translation' },
  ja: { original: '原画像', translation: '翻訳画像', unstarted: '画像翻訳は未開始です', queued: '画像翻訳の待機中', running: '画像を翻訳中', ready: '翻訳画像を表示できます。お好きな時に切り替えてください。', failed: '画像翻訳に失敗しました', cancelled: '画像翻訳をキャンセルしました', expired: '画像翻訳の期限が切れました', notRequired: '画像翻訳は不要です', alreadyChinese: '原画像はすでに中国語です', noText: '料理写真に翻訳する文字はありません', originalSave: 'この端末の原画像', translationSave: 'この端末の翻訳画像', pending: '端末に未保存', saving: '端末に保存中', saved: '端末に保存済み', saveFailed: '未保存のためオフラインでは表示できません。', retrySave: '画像の保存を再試行', missingTranslation: 'この端末に翻訳画像がありません。オンラインで保存してください。', choiceFailed: '画像の選択を保存できませんでした', retryChoice: '選択の保存を再試行', readFailed: '画像翻訳を更新できませんでした' },
  ko: { original: '원본', translation: '번역 이미지', unstarted: '이미지 번역 시작 전', queued: '이미지 번역 대기 중', running: '이미지 번역 중', ready: '번역 이미지가 준비됐어요. 원할 때 전환하세요.', failed: '이미지 번역 실패', cancelled: '이미지 번역 취소됨', expired: '이미지 번역 만료됨', notRequired: '이미지 번역이 필요하지 않아요', alreadyChinese: '원본이 이미 중국어예요', noText: '음식 사진에 번역할 글자가 없어요', originalSave: '이 기기의 원본', translationSave: '이 기기의 번역 이미지', pending: '기기에 저장되지 않음', saving: '기기에 저장 중', saved: '기기에 저장됨', saveFailed: '저장되지 않아 오프라인에서 볼 수 없어요.', retrySave: '이미지 저장 다시 시도', missingTranslation: '기기에 번역 이미지가 없어요. 온라인에서 저장하세요.', choiceFailed: '이미지 선택을 저장하지 못했어요', retryChoice: '선택 저장 다시 시도', readFailed: '이미지 번역을 새로고침하지 못했어요' },
  es: { original: 'Original', translation: 'Traducida', unstarted: 'Traducción de imagen sin iniciar', queued: 'Traducción de imagen en cola', running: 'Traduciendo la imagen', ready: 'La imagen traducida está lista. Cámbiala cuando quieras.', failed: 'Falló la traducción de imagen', cancelled: 'Traducción de imagen cancelada', expired: 'La traducción de imagen caducó', notRequired: 'No hace falta traducir la imagen', alreadyChinese: 'El original ya está en chino', noText: 'No hay texto que traducir en esta foto del plato', originalSave: 'Original en este dispositivo', translationSave: 'Traducción en este dispositivo', pending: 'Sin guardar en el dispositivo', saving: 'Guardando en el dispositivo', saved: 'Guardada en el dispositivo', saveFailed: 'Sin guardar. No disponible sin conexión.', retrySave: 'Reintentar guardar imagen', missingTranslation: 'La imagen traducida no está en el dispositivo. Guárdala con conexión.', choiceFailed: 'No se pudo guardar la imagen elegida', retryChoice: 'Reintentar guardar elección', readFailed: 'No se pudo actualizar la traducción de imagen' },
  'zh-CN': { original: '原图', translation: '译图', unstarted: '译图尚未开始', queued: '译图排队中', running: '正在生成译图', ready: '译图已准备好，可按需切换。', failed: '译图生成失败', cancelled: '译图已取消', expired: '译图已过期', notRequired: '此图片无须生成译图', alreadyChinese: '原图已是中文，保留原图展示', noText: '这张菜品照片没有需要翻译的文字', originalSave: '原图本机保存', translationSave: '译图本机保存', pending: '尚未保存到本机', saving: '正在保存到本机', saved: '已保存到本机', saveFailed: '尚未保存，离线时无法使用。', retrySave: '重试保存图片', missingTranslation: '本机没有可用译图，请联网后保存。', choiceFailed: '未能保存原译选择', retryChoice: '重试保存选择', readFailed: '未能刷新译图状态' }
};
function getImagesCopy(language) { return COPY[language] || COPY.en; }
module.exports = { getImagesCopy };
